version: 2

updates:

- package-ecosystem: gomod
  directory: /
  target-branch: prod-staging
  schedule:
    interval: weekly
    day: sunday
    time: '09:00'
  commit-message:
    prefix: gomod # Prefix messages with
    include: scope # List all updated dependencies
  ignore:
    # HACK: do these manually, these aren't tagged in a super go-friendly way
    - dependency-name: "unikraft.com/cloud/sdk"
  groups:
    go-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: sunday
    time: '09:00'
  groups:
    github-deps:
      applies-to: version-updates
      patterns:
        - "*"
