# https://taskfile.dev
version: 3

includes:
  go:
    taskfile: https://github.com/unikraft-cloud/x.git//Taskfile.go.yml?ref=prod-staging
    vars:
      go_module: unikraft.com/cli

# TODO: svu?

tasks:
  default:
    cmds:
    - task: cli

  cli:
    cmds:
    - task: go:build
      vars:
        package: ./cmd/unikraft

  lint:
    cmds:
      - task: go:lint

  test:
    cmds:
    - task: go:test

  integration:
    cmds:
    - task: go:test
      vars:
        go_tags: "integration"
        package: ./cmd/unikraft

  integration-update:
    cmd: >-
      go test -v ./cmd/unikraft -tags integration --update

  docs:
    cmds:
    - go run ./tools/gencli docs ./dist/docs
    - go run ./tools/gencli man --compress ./dist/man
