name: bump-go

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bump-go:
    uses: unikraft-cloud/x/.github/workflows/bump-go.yaml@prod-staging
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}
