name: check/pr

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [staging]

jobs:
  check-pr:
    # runs-on: ubuntu-latest
    runs-on: ${{ github.event.pull_request.head.repo.fork && 'ubuntu-latest' || 'arc-unikraft-cli-ubuntu24.04-standard' }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run check-pr
      uses: unikraft-cloud/x/.github/actions/check-pr@prod-staging
