name: check/pr

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [staging]

jobs:
  pr-check:
    uses: unikraft-cloud/x/.github/workflows/check-pr.yaml@prod-staging

