name: tag

on:
  push:
    branches:
    - staging
    - stable

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v6
      with:
        go-version: 1.24.5

    - name: Set Go variables
      id: goenv
      run: |
        {
          echo "cache=$(go env GOCACHE)"
          echo "modcache=$(go env GOMODCACHE)"
          echo "mod=$(go env GOMOD)"
        } >>"$GITHUB_OUTPUT"

    - name: Go caches
      uses: actions/cache@v5
      with:
        path: |
          ${{ steps.goenv.outputs.cache }}
          ${{ steps.goenv.outputs.modcache }}
        key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles(steps.goenv.outputs.mod) }}
        restore-keys: |
          ${{ github.job }}-${{ runner.os }}-go-

    - name: Fetch all tags
      shell: bash
      run: git fetch --force --tags

    - name: Login to GitHub
      shell: bash
      run: git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

    - name: Generate next stable version
      shell: bash
      if: ${{ github.ref == 'refs/heads/stable' }}
      run: |
        git config user.name "Unikraft Bot"
        git config user.email "monkey@unikraft.com"
        VERSION=$(make --no-print-directory next-stable)
        git tag -a "${VERSION}" -m "${VERSION}"
        git push -u origin "${VERSION}"

    - name: Generate next staging version
      shell: bash
      if: ${{ github.ref == 'refs/heads/staging' }}
      run: |
        git config user.name "Unikraft Bot"
        git config user.email "monkey@unikraft.com"
        VERSION=$(make --no-print-directory next-staging)
        git tag -a "${VERSION}" -m "${VERSION}"
        git push -u origin "${VERSION}"
